name: Manage my README.md
on:
  push:
    branches:
      - main
  schedule:
    # Runs 
    - cron: '0 0 * * *'
  workflow_dispatch:
    
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@sameer330"
          gh_token: ${{ secrets.MY_GH_TOKEN }}

